version: '3'

services:
  #Back-end Spring Boot Application
  boot-app:
    build: ./employeeService-master
    container_name: boot-app
    ports:
      - 8080:8080

  #Fron-end Angular Application
  angular-ui:
    build: ./EmployeeManagement
    container_name: angular-ui
    ports:
      - 4200:80
    links:
      - boot-app